// flow-typed signature: b09489a1342463cae86ba3c521a72ec5
// flow-typed version: <<STUB>>/hellojs_v^2.0.0-4/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hellojs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hellojs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hellojs/assets/css-social-buttons/site/html5slider' {
  declare module.exports: any;
}

declare module 'hellojs/assets/css-social-buttons/site/size-change' {
  declare module.exports: any;
}

declare module 'hellojs/assets/expect/index' {
  declare module.exports: any;
}

declare module 'hellojs/assets/index' {
  declare module.exports: any;
}

declare module 'hellojs/assets/json2/cycle' {
  declare module.exports: any;
}

declare module 'hellojs/assets/json2/json_parse_state' {
  declare module.exports: any;
}

declare module 'hellojs/assets/json2/json_parse' {
  declare module.exports: any;
}

declare module 'hellojs/assets/json2/json' {
  declare module.exports: any;
}

declare module 'hellojs/assets/json2/json2' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/build/fragments/amd-post' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/build/fragments/amd-pre' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/build/fragments/extern-post' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/build/fragments/extern-pre' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/build/fragments/source-references' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/build/knockout-raw' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/dist/knockout.debug' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/dist/knockout' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/Gruntfile' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/bindingAttributeSyntax' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/bindingProvider' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/attr' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/checked' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/click' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/css' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/enableDisable' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/event' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/foreach' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/hasfocus' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/html' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/ifIfnotWith' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/options' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/selectedOptions' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/style' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/submit' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/text' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/textInput' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/uniqueName' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/value' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/defaultBindings/visible' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/editDetection/arrayToDomNodeChildren' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/editDetection/compareArrays' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/expressionRewriting' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/binding/selectExtensions' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/components/componentBinding' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/components/customElements' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/components/defaultLoader' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/components/loaderRegistry' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/google-closure-compiler-utils' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/memoization' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/namespace' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/options' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/subscribables/dependencyDetection' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/subscribables/dependentObservable' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/subscribables/extenders' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/subscribables/mappingHelpers' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/subscribables/observable' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/subscribables/observableArray.changeTracking' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/subscribables/observableArray' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/subscribables/subscribable' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/tasks' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/templating/jquery.tmpl/jqueryTmplTemplateEngine' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/templating/native/nativeTemplateEngine' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/templating/templateEngine' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/templating/templateRewriting' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/templating/templateSources' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/templating/templating' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/utils.domData' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/utils.domManipulation' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/utils.domNodeDisposal' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/utils' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/version' {
  declare module.exports: any;
}

declare module 'hellojs/assets/knockout/src/virtualElements' {
  declare module.exports: any;
}

declare module 'hellojs/assets/mocha/mocha' {
  declare module.exports: any;
}

declare module 'hellojs/assets/requirejs/require' {
  declare module.exports: any;
}

declare module 'hellojs/assets/sinonjs/sinon' {
  declare module.exports: any;
}

declare module 'hellojs/demos/client_ids' {
  declare module.exports: any;
}

declare module 'hellojs/demos/Collage/fabric' {
  declare module.exports: any;
}

declare module 'hellojs/demos/FilePicker/filePicker' {
  declare module.exports: any;
}

declare module 'hellojs/demos/helper/alert-https' {
  declare module.exports: any;
}

declare module 'hellojs/demos/helper/uiFiles' {
  declare module.exports: any;
}

declare module 'hellojs/demos/helper/uiProfile' {
  declare module.exports: any;
}

declare module 'hellojs/dist/hello.all' {
  declare module.exports: any;
}

declare module 'hellojs/dist/hello' {
  declare module.exports: any;
}

declare module 'hellojs/gulpfile' {
  declare module.exports: any;
}

declare module 'hellojs/src/hello.all' {
  declare module.exports: any;
}

declare module 'hellojs/src/hello.chromeapp' {
  declare module.exports: any;
}

declare module 'hellojs/src/hello' {
  declare module.exports: any;
}

declare module 'hellojs/src/hello.phonegap' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/amazon' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/bikeindex' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/box' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/dropbox' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/facebook' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/flickr' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/foursquare' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/github' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/google' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/instagram' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/joinme' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/linkedin' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/soundcloud' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/tumblr' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/twitter' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/vimeo' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/vk' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/windows' {
  declare module.exports: any;
}

declare module 'hellojs/src/modules/yahoo' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/atob' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/Blob' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/Blob.js/Blob' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/css-social-buttons/site/html5slider' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/css-social-buttons/site/size-change' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/errorResponse' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/expect/index' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/json2/cycle' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/json2/json_parse_state' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/json2/json_parse' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/json2/json' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/json2/json2' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/build/fragments/amd-post' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/build/fragments/amd-pre' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/build/fragments/extern-post' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/build/fragments/extern-pre' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/build/fragments/source-references' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/build/knockout-raw' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/dist/knockout.debug' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/dist/knockout' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/Gruntfile' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/bindingAttributeSyntax' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/bindingProvider' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/attr' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/checked' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/click' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/css' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/enableDisable' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/event' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/foreach' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/hasfocus' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/html' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/ifIfnotWith' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/options' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/selectedOptions' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/style' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/submit' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/text' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/textInput' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/uniqueName' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/value' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/visible' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/editDetection/arrayToDomNodeChildren' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/editDetection/compareArrays' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/expressionRewriting' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/binding/selectExtensions' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/components/componentBinding' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/components/customElements' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/components/defaultLoader' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/components/loaderRegistry' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/google-closure-compiler-utils' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/memoization' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/namespace' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/options' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/subscribables/dependencyDetection' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/subscribables/dependentObservable' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/subscribables/extenders' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/subscribables/mappingHelpers' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/subscribables/observable' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/subscribables/observableArray.changeTracking' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/subscribables/observableArray' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/subscribables/subscribable' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/tasks' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/templating/jquery.tmpl/jqueryTmplTemplateEngine' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/templating/native/nativeTemplateEngine' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/templating/templateEngine' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/templating/templateRewriting' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/templating/templateSources' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/templating/templating' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/utils.domData' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/utils.domManipulation' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/utils.domNodeDisposal' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/utils' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/version' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/knockout/src/virtualElements' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/mocha/mocha' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/requirejs/require' {
  declare module.exports: any;
}

declare module 'hellojs/test/lib/sinonjs/sinon' {
  declare module.exports: any;
}

declare module 'hellojs/test/mocha_config' {
  declare module.exports: any;
}

declare module 'hellojs/test/mocha_run' {
  declare module.exports: any;
}

declare module 'hellojs/test/setup' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/e2e/modules' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/e2e/requireable' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/index' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/core/hello.api' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/core/hello.events' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/core/hello.getAuthResponse' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/core/hello.init' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/core/hello.login' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/core/hello.logout' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/core/hello.use' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/core/proxyHandler' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/core/responseHandler' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/core/session.monitor' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/ext/chromeapp/popup' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/modules/api' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/modules/apiMe' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/modules/apiMeAlbum' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/modules/apiMeAlbums' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/modules/apiMeFriends' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/modules/apiMePhotos' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/modules/helper' {
  declare module.exports: any;
}

declare module 'hellojs/test/specs/unit/modules/index' {
  declare module.exports: any;
}

declare module 'hellojs/test/stubs/endpoints' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hellojs/assets/css-social-buttons/site/html5slider.js' {
  declare module.exports: $Exports<'hellojs/assets/css-social-buttons/site/html5slider'>;
}
declare module 'hellojs/assets/css-social-buttons/site/size-change.js' {
  declare module.exports: $Exports<'hellojs/assets/css-social-buttons/site/size-change'>;
}
declare module 'hellojs/assets/expect/index.js' {
  declare module.exports: $Exports<'hellojs/assets/expect/index'>;
}
declare module 'hellojs/assets/index.js' {
  declare module.exports: $Exports<'hellojs/assets/index'>;
}
declare module 'hellojs/assets/json2/cycle.js' {
  declare module.exports: $Exports<'hellojs/assets/json2/cycle'>;
}
declare module 'hellojs/assets/json2/json_parse_state.js' {
  declare module.exports: $Exports<'hellojs/assets/json2/json_parse_state'>;
}
declare module 'hellojs/assets/json2/json_parse.js' {
  declare module.exports: $Exports<'hellojs/assets/json2/json_parse'>;
}
declare module 'hellojs/assets/json2/json.js' {
  declare module.exports: $Exports<'hellojs/assets/json2/json'>;
}
declare module 'hellojs/assets/json2/json2.js' {
  declare module.exports: $Exports<'hellojs/assets/json2/json2'>;
}
declare module 'hellojs/assets/knockout/build/fragments/amd-post.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/build/fragments/amd-post'>;
}
declare module 'hellojs/assets/knockout/build/fragments/amd-pre.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/build/fragments/amd-pre'>;
}
declare module 'hellojs/assets/knockout/build/fragments/extern-post.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/build/fragments/extern-post'>;
}
declare module 'hellojs/assets/knockout/build/fragments/extern-pre.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/build/fragments/extern-pre'>;
}
declare module 'hellojs/assets/knockout/build/fragments/source-references.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/build/fragments/source-references'>;
}
declare module 'hellojs/assets/knockout/build/knockout-raw.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/build/knockout-raw'>;
}
declare module 'hellojs/assets/knockout/dist/knockout.debug.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/dist/knockout.debug'>;
}
declare module 'hellojs/assets/knockout/dist/knockout.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/dist/knockout'>;
}
declare module 'hellojs/assets/knockout/Gruntfile.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/Gruntfile'>;
}
declare module 'hellojs/assets/knockout/src/binding/bindingAttributeSyntax.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/bindingAttributeSyntax'>;
}
declare module 'hellojs/assets/knockout/src/binding/bindingProvider.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/bindingProvider'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/attr.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/attr'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/checked.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/checked'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/click.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/click'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/css.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/css'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/enableDisable.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/enableDisable'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/event.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/event'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/foreach.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/foreach'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/hasfocus.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/hasfocus'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/html.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/html'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/ifIfnotWith.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/ifIfnotWith'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/options.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/options'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/selectedOptions.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/selectedOptions'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/style.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/style'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/submit.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/submit'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/text.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/text'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/textInput.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/textInput'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/uniqueName.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/uniqueName'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/value.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/value'>;
}
declare module 'hellojs/assets/knockout/src/binding/defaultBindings/visible.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/defaultBindings/visible'>;
}
declare module 'hellojs/assets/knockout/src/binding/editDetection/arrayToDomNodeChildren.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/editDetection/arrayToDomNodeChildren'>;
}
declare module 'hellojs/assets/knockout/src/binding/editDetection/compareArrays.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/editDetection/compareArrays'>;
}
declare module 'hellojs/assets/knockout/src/binding/expressionRewriting.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/expressionRewriting'>;
}
declare module 'hellojs/assets/knockout/src/binding/selectExtensions.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/binding/selectExtensions'>;
}
declare module 'hellojs/assets/knockout/src/components/componentBinding.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/components/componentBinding'>;
}
declare module 'hellojs/assets/knockout/src/components/customElements.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/components/customElements'>;
}
declare module 'hellojs/assets/knockout/src/components/defaultLoader.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/components/defaultLoader'>;
}
declare module 'hellojs/assets/knockout/src/components/loaderRegistry.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/components/loaderRegistry'>;
}
declare module 'hellojs/assets/knockout/src/google-closure-compiler-utils.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/google-closure-compiler-utils'>;
}
declare module 'hellojs/assets/knockout/src/memoization.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/memoization'>;
}
declare module 'hellojs/assets/knockout/src/namespace.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/namespace'>;
}
declare module 'hellojs/assets/knockout/src/options.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/options'>;
}
declare module 'hellojs/assets/knockout/src/subscribables/dependencyDetection.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/subscribables/dependencyDetection'>;
}
declare module 'hellojs/assets/knockout/src/subscribables/dependentObservable.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/subscribables/dependentObservable'>;
}
declare module 'hellojs/assets/knockout/src/subscribables/extenders.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/subscribables/extenders'>;
}
declare module 'hellojs/assets/knockout/src/subscribables/mappingHelpers.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/subscribables/mappingHelpers'>;
}
declare module 'hellojs/assets/knockout/src/subscribables/observable.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/subscribables/observable'>;
}
declare module 'hellojs/assets/knockout/src/subscribables/observableArray.changeTracking.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/subscribables/observableArray.changeTracking'>;
}
declare module 'hellojs/assets/knockout/src/subscribables/observableArray.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/subscribables/observableArray'>;
}
declare module 'hellojs/assets/knockout/src/subscribables/subscribable.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/subscribables/subscribable'>;
}
declare module 'hellojs/assets/knockout/src/tasks.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/tasks'>;
}
declare module 'hellojs/assets/knockout/src/templating/jquery.tmpl/jqueryTmplTemplateEngine.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/templating/jquery.tmpl/jqueryTmplTemplateEngine'>;
}
declare module 'hellojs/assets/knockout/src/templating/native/nativeTemplateEngine.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/templating/native/nativeTemplateEngine'>;
}
declare module 'hellojs/assets/knockout/src/templating/templateEngine.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/templating/templateEngine'>;
}
declare module 'hellojs/assets/knockout/src/templating/templateRewriting.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/templating/templateRewriting'>;
}
declare module 'hellojs/assets/knockout/src/templating/templateSources.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/templating/templateSources'>;
}
declare module 'hellojs/assets/knockout/src/templating/templating.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/templating/templating'>;
}
declare module 'hellojs/assets/knockout/src/utils.domData.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/utils.domData'>;
}
declare module 'hellojs/assets/knockout/src/utils.domManipulation.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/utils.domManipulation'>;
}
declare module 'hellojs/assets/knockout/src/utils.domNodeDisposal.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/utils.domNodeDisposal'>;
}
declare module 'hellojs/assets/knockout/src/utils.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/utils'>;
}
declare module 'hellojs/assets/knockout/src/version.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/version'>;
}
declare module 'hellojs/assets/knockout/src/virtualElements.js' {
  declare module.exports: $Exports<'hellojs/assets/knockout/src/virtualElements'>;
}
declare module 'hellojs/assets/mocha/mocha.js' {
  declare module.exports: $Exports<'hellojs/assets/mocha/mocha'>;
}
declare module 'hellojs/assets/requirejs/require.js' {
  declare module.exports: $Exports<'hellojs/assets/requirejs/require'>;
}
declare module 'hellojs/assets/sinonjs/sinon.js' {
  declare module.exports: $Exports<'hellojs/assets/sinonjs/sinon'>;
}
declare module 'hellojs/demos/client_ids.js' {
  declare module.exports: $Exports<'hellojs/demos/client_ids'>;
}
declare module 'hellojs/demos/Collage/fabric.js' {
  declare module.exports: $Exports<'hellojs/demos/Collage/fabric'>;
}
declare module 'hellojs/demos/FilePicker/filePicker.js' {
  declare module.exports: $Exports<'hellojs/demos/FilePicker/filePicker'>;
}
declare module 'hellojs/demos/helper/alert-https.js' {
  declare module.exports: $Exports<'hellojs/demos/helper/alert-https'>;
}
declare module 'hellojs/demos/helper/uiFiles.js' {
  declare module.exports: $Exports<'hellojs/demos/helper/uiFiles'>;
}
declare module 'hellojs/demos/helper/uiProfile.js' {
  declare module.exports: $Exports<'hellojs/demos/helper/uiProfile'>;
}
declare module 'hellojs/dist/hello.all.js' {
  declare module.exports: $Exports<'hellojs/dist/hello.all'>;
}
declare module 'hellojs/dist/hello.js' {
  declare module.exports: $Exports<'hellojs/dist/hello'>;
}
declare module 'hellojs/gulpfile.js' {
  declare module.exports: $Exports<'hellojs/gulpfile'>;
}
declare module 'hellojs/src/hello.all.js' {
  declare module.exports: $Exports<'hellojs/src/hello.all'>;
}
declare module 'hellojs/src/hello.chromeapp.js' {
  declare module.exports: $Exports<'hellojs/src/hello.chromeapp'>;
}
declare module 'hellojs/src/hello.js' {
  declare module.exports: $Exports<'hellojs/src/hello'>;
}
declare module 'hellojs/src/hello.phonegap.js' {
  declare module.exports: $Exports<'hellojs/src/hello.phonegap'>;
}
declare module 'hellojs/src/modules/amazon.js' {
  declare module.exports: $Exports<'hellojs/src/modules/amazon'>;
}
declare module 'hellojs/src/modules/bikeindex.js' {
  declare module.exports: $Exports<'hellojs/src/modules/bikeindex'>;
}
declare module 'hellojs/src/modules/box.js' {
  declare module.exports: $Exports<'hellojs/src/modules/box'>;
}
declare module 'hellojs/src/modules/dropbox.js' {
  declare module.exports: $Exports<'hellojs/src/modules/dropbox'>;
}
declare module 'hellojs/src/modules/facebook.js' {
  declare module.exports: $Exports<'hellojs/src/modules/facebook'>;
}
declare module 'hellojs/src/modules/flickr.js' {
  declare module.exports: $Exports<'hellojs/src/modules/flickr'>;
}
declare module 'hellojs/src/modules/foursquare.js' {
  declare module.exports: $Exports<'hellojs/src/modules/foursquare'>;
}
declare module 'hellojs/src/modules/github.js' {
  declare module.exports: $Exports<'hellojs/src/modules/github'>;
}
declare module 'hellojs/src/modules/google.js' {
  declare module.exports: $Exports<'hellojs/src/modules/google'>;
}
declare module 'hellojs/src/modules/instagram.js' {
  declare module.exports: $Exports<'hellojs/src/modules/instagram'>;
}
declare module 'hellojs/src/modules/joinme.js' {
  declare module.exports: $Exports<'hellojs/src/modules/joinme'>;
}
declare module 'hellojs/src/modules/linkedin.js' {
  declare module.exports: $Exports<'hellojs/src/modules/linkedin'>;
}
declare module 'hellojs/src/modules/soundcloud.js' {
  declare module.exports: $Exports<'hellojs/src/modules/soundcloud'>;
}
declare module 'hellojs/src/modules/tumblr.js' {
  declare module.exports: $Exports<'hellojs/src/modules/tumblr'>;
}
declare module 'hellojs/src/modules/twitter.js' {
  declare module.exports: $Exports<'hellojs/src/modules/twitter'>;
}
declare module 'hellojs/src/modules/vimeo.js' {
  declare module.exports: $Exports<'hellojs/src/modules/vimeo'>;
}
declare module 'hellojs/src/modules/vk.js' {
  declare module.exports: $Exports<'hellojs/src/modules/vk'>;
}
declare module 'hellojs/src/modules/windows.js' {
  declare module.exports: $Exports<'hellojs/src/modules/windows'>;
}
declare module 'hellojs/src/modules/yahoo.js' {
  declare module.exports: $Exports<'hellojs/src/modules/yahoo'>;
}
declare module 'hellojs/test/lib/atob.js' {
  declare module.exports: $Exports<'hellojs/test/lib/atob'>;
}
declare module 'hellojs/test/lib/Blob.js' {
  declare module.exports: $Exports<'hellojs/test/lib/Blob'>;
}
declare module 'hellojs/test/lib/Blob.js/Blob.js' {
  declare module.exports: $Exports<'hellojs/test/lib/Blob.js/Blob'>;
}
declare module 'hellojs/test/lib/css-social-buttons/site/html5slider.js' {
  declare module.exports: $Exports<'hellojs/test/lib/css-social-buttons/site/html5slider'>;
}
declare module 'hellojs/test/lib/css-social-buttons/site/size-change.js' {
  declare module.exports: $Exports<'hellojs/test/lib/css-social-buttons/site/size-change'>;
}
declare module 'hellojs/test/lib/errorResponse.js' {
  declare module.exports: $Exports<'hellojs/test/lib/errorResponse'>;
}
declare module 'hellojs/test/lib/expect/index.js' {
  declare module.exports: $Exports<'hellojs/test/lib/expect/index'>;
}
declare module 'hellojs/test/lib/json2/cycle.js' {
  declare module.exports: $Exports<'hellojs/test/lib/json2/cycle'>;
}
declare module 'hellojs/test/lib/json2/json_parse_state.js' {
  declare module.exports: $Exports<'hellojs/test/lib/json2/json_parse_state'>;
}
declare module 'hellojs/test/lib/json2/json_parse.js' {
  declare module.exports: $Exports<'hellojs/test/lib/json2/json_parse'>;
}
declare module 'hellojs/test/lib/json2/json.js' {
  declare module.exports: $Exports<'hellojs/test/lib/json2/json'>;
}
declare module 'hellojs/test/lib/json2/json2.js' {
  declare module.exports: $Exports<'hellojs/test/lib/json2/json2'>;
}
declare module 'hellojs/test/lib/knockout/build/fragments/amd-post.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/build/fragments/amd-post'>;
}
declare module 'hellojs/test/lib/knockout/build/fragments/amd-pre.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/build/fragments/amd-pre'>;
}
declare module 'hellojs/test/lib/knockout/build/fragments/extern-post.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/build/fragments/extern-post'>;
}
declare module 'hellojs/test/lib/knockout/build/fragments/extern-pre.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/build/fragments/extern-pre'>;
}
declare module 'hellojs/test/lib/knockout/build/fragments/source-references.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/build/fragments/source-references'>;
}
declare module 'hellojs/test/lib/knockout/build/knockout-raw.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/build/knockout-raw'>;
}
declare module 'hellojs/test/lib/knockout/dist/knockout.debug.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/dist/knockout.debug'>;
}
declare module 'hellojs/test/lib/knockout/dist/knockout.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/dist/knockout'>;
}
declare module 'hellojs/test/lib/knockout/Gruntfile.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/Gruntfile'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/bindingAttributeSyntax.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/bindingAttributeSyntax'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/bindingProvider.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/bindingProvider'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/attr.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/attr'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/checked.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/checked'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/click.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/click'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/css.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/css'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/enableDisable.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/enableDisable'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/event.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/event'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/foreach.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/foreach'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/hasfocus.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/hasfocus'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/html.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/html'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/ifIfnotWith.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/ifIfnotWith'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/options.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/options'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/selectedOptions.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/selectedOptions'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/style.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/style'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/submit.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/submit'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/text.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/text'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/textInput.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/textInput'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/uniqueName.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/uniqueName'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/value.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/value'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/defaultBindings/visible.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/defaultBindings/visible'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/editDetection/arrayToDomNodeChildren.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/editDetection/arrayToDomNodeChildren'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/editDetection/compareArrays.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/editDetection/compareArrays'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/expressionRewriting.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/expressionRewriting'>;
}
declare module 'hellojs/test/lib/knockout/src/binding/selectExtensions.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/binding/selectExtensions'>;
}
declare module 'hellojs/test/lib/knockout/src/components/componentBinding.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/components/componentBinding'>;
}
declare module 'hellojs/test/lib/knockout/src/components/customElements.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/components/customElements'>;
}
declare module 'hellojs/test/lib/knockout/src/components/defaultLoader.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/components/defaultLoader'>;
}
declare module 'hellojs/test/lib/knockout/src/components/loaderRegistry.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/components/loaderRegistry'>;
}
declare module 'hellojs/test/lib/knockout/src/google-closure-compiler-utils.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/google-closure-compiler-utils'>;
}
declare module 'hellojs/test/lib/knockout/src/memoization.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/memoization'>;
}
declare module 'hellojs/test/lib/knockout/src/namespace.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/namespace'>;
}
declare module 'hellojs/test/lib/knockout/src/options.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/options'>;
}
declare module 'hellojs/test/lib/knockout/src/subscribables/dependencyDetection.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/subscribables/dependencyDetection'>;
}
declare module 'hellojs/test/lib/knockout/src/subscribables/dependentObservable.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/subscribables/dependentObservable'>;
}
declare module 'hellojs/test/lib/knockout/src/subscribables/extenders.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/subscribables/extenders'>;
}
declare module 'hellojs/test/lib/knockout/src/subscribables/mappingHelpers.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/subscribables/mappingHelpers'>;
}
declare module 'hellojs/test/lib/knockout/src/subscribables/observable.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/subscribables/observable'>;
}
declare module 'hellojs/test/lib/knockout/src/subscribables/observableArray.changeTracking.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/subscribables/observableArray.changeTracking'>;
}
declare module 'hellojs/test/lib/knockout/src/subscribables/observableArray.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/subscribables/observableArray'>;
}
declare module 'hellojs/test/lib/knockout/src/subscribables/subscribable.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/subscribables/subscribable'>;
}
declare module 'hellojs/test/lib/knockout/src/tasks.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/tasks'>;
}
declare module 'hellojs/test/lib/knockout/src/templating/jquery.tmpl/jqueryTmplTemplateEngine.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/templating/jquery.tmpl/jqueryTmplTemplateEngine'>;
}
declare module 'hellojs/test/lib/knockout/src/templating/native/nativeTemplateEngine.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/templating/native/nativeTemplateEngine'>;
}
declare module 'hellojs/test/lib/knockout/src/templating/templateEngine.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/templating/templateEngine'>;
}
declare module 'hellojs/test/lib/knockout/src/templating/templateRewriting.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/templating/templateRewriting'>;
}
declare module 'hellojs/test/lib/knockout/src/templating/templateSources.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/templating/templateSources'>;
}
declare module 'hellojs/test/lib/knockout/src/templating/templating.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/templating/templating'>;
}
declare module 'hellojs/test/lib/knockout/src/utils.domData.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/utils.domData'>;
}
declare module 'hellojs/test/lib/knockout/src/utils.domManipulation.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/utils.domManipulation'>;
}
declare module 'hellojs/test/lib/knockout/src/utils.domNodeDisposal.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/utils.domNodeDisposal'>;
}
declare module 'hellojs/test/lib/knockout/src/utils.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/utils'>;
}
declare module 'hellojs/test/lib/knockout/src/version.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/version'>;
}
declare module 'hellojs/test/lib/knockout/src/virtualElements.js' {
  declare module.exports: $Exports<'hellojs/test/lib/knockout/src/virtualElements'>;
}
declare module 'hellojs/test/lib/mocha/mocha.js' {
  declare module.exports: $Exports<'hellojs/test/lib/mocha/mocha'>;
}
declare module 'hellojs/test/lib/requirejs/require.js' {
  declare module.exports: $Exports<'hellojs/test/lib/requirejs/require'>;
}
declare module 'hellojs/test/lib/sinonjs/sinon.js' {
  declare module.exports: $Exports<'hellojs/test/lib/sinonjs/sinon'>;
}
declare module 'hellojs/test/mocha_config.js' {
  declare module.exports: $Exports<'hellojs/test/mocha_config'>;
}
declare module 'hellojs/test/mocha_run.js' {
  declare module.exports: $Exports<'hellojs/test/mocha_run'>;
}
declare module 'hellojs/test/setup.js' {
  declare module.exports: $Exports<'hellojs/test/setup'>;
}
declare module 'hellojs/test/specs/e2e/modules.js' {
  declare module.exports: $Exports<'hellojs/test/specs/e2e/modules'>;
}
declare module 'hellojs/test/specs/e2e/requireable.js' {
  declare module.exports: $Exports<'hellojs/test/specs/e2e/requireable'>;
}
declare module 'hellojs/test/specs/index.js' {
  declare module.exports: $Exports<'hellojs/test/specs/index'>;
}
declare module 'hellojs/test/specs/unit/core/hello.api.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/core/hello.api'>;
}
declare module 'hellojs/test/specs/unit/core/hello.events.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/core/hello.events'>;
}
declare module 'hellojs/test/specs/unit/core/hello.getAuthResponse.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/core/hello.getAuthResponse'>;
}
declare module 'hellojs/test/specs/unit/core/hello.init.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/core/hello.init'>;
}
declare module 'hellojs/test/specs/unit/core/hello.login.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/core/hello.login'>;
}
declare module 'hellojs/test/specs/unit/core/hello.logout.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/core/hello.logout'>;
}
declare module 'hellojs/test/specs/unit/core/hello.use.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/core/hello.use'>;
}
declare module 'hellojs/test/specs/unit/core/proxyHandler.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/core/proxyHandler'>;
}
declare module 'hellojs/test/specs/unit/core/responseHandler.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/core/responseHandler'>;
}
declare module 'hellojs/test/specs/unit/core/session.monitor.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/core/session.monitor'>;
}
declare module 'hellojs/test/specs/unit/ext/chromeapp/popup.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/ext/chromeapp/popup'>;
}
declare module 'hellojs/test/specs/unit/modules/api.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/modules/api'>;
}
declare module 'hellojs/test/specs/unit/modules/apiMe.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/modules/apiMe'>;
}
declare module 'hellojs/test/specs/unit/modules/apiMeAlbum.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/modules/apiMeAlbum'>;
}
declare module 'hellojs/test/specs/unit/modules/apiMeAlbums.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/modules/apiMeAlbums'>;
}
declare module 'hellojs/test/specs/unit/modules/apiMeFriends.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/modules/apiMeFriends'>;
}
declare module 'hellojs/test/specs/unit/modules/apiMePhotos.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/modules/apiMePhotos'>;
}
declare module 'hellojs/test/specs/unit/modules/helper.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/modules/helper'>;
}
declare module 'hellojs/test/specs/unit/modules/index.js' {
  declare module.exports: $Exports<'hellojs/test/specs/unit/modules/index'>;
}
declare module 'hellojs/test/stubs/endpoints.js' {
  declare module.exports: $Exports<'hellojs/test/stubs/endpoints'>;
}
