// flow-typed signature: e14ab1cfc550cae1d8630092af2f004a
// flow-typed version: <<STUB>>/react-speech-recognition_v^2.0.4/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-speech-recognition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-speech-recognition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-speech-recognition/dist/SpeechRecognition' {
  declare module.exports: any;
}

declare module 'react-speech-recognition/lib/index' {
  declare module.exports: any;
}

declare module 'react-speech-recognition/lib/SpeechRecognition' {
  declare module.exports: any;
}

declare module 'react-speech-recognition/src/index' {
  declare module.exports: any;
}

declare module 'react-speech-recognition/src/SpeechRecognition' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-speech-recognition/dist/SpeechRecognition.js' {
  declare module.exports: $Exports<'react-speech-recognition/dist/SpeechRecognition'>;
}
declare module 'react-speech-recognition/lib/index.js' {
  declare module.exports: $Exports<'react-speech-recognition/lib/index'>;
}
declare module 'react-speech-recognition/lib/SpeechRecognition.js' {
  declare module.exports: $Exports<'react-speech-recognition/lib/SpeechRecognition'>;
}
declare module 'react-speech-recognition/src/index.js' {
  declare module.exports: $Exports<'react-speech-recognition/src/index'>;
}
declare module 'react-speech-recognition/src/SpeechRecognition.js' {
  declare module.exports: $Exports<'react-speech-recognition/src/SpeechRecognition'>;
}
